/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oddshou_testall_jniClass_JniUtils */

#ifndef _Included_com_oddshou_testall_jniClass_JniUtils
#define _Included_com_oddshou_testall_jniClass_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oddshou_testall_jniClass_JniUtils
 * Method:    getFirstMethed
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oddshou_testall_jniClass_JniUtils_getFirstMethed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
